[package]

name = "async"
version = "0.0.1"
authors = ["Clark Gaebel <cgaebel@mozilla.com>"]

[dependencies.ivar]

git = "https://github.com/cgaebel/ivar.git"

[dependencies.cloq]

git = "https://github.com/cgaebel/cloq.git"